image: node:latest

build:
  stage: build
  script:
    - npm ci
    - npm run lint

publish:
  stage: publish
  script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">>.npmrc
    - npm ci
    - npm run build
    - npm publish
  only:
    - main