image: node:latest

stages:
  - build
  # - publish

build:
  stage: build
  script:
    - npm ci
    - npm run lint
    - npm run build
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">>.npmrc
    - npm publish

# publish:
#   stage: publish
#   script:
#     - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
#     - npm publish
#   only:
#     - main